### ISSUE TITLE
How to upload a mp3 File

### ISSUE THREAD

**Issue by MOEVR** [rampatra/jbot#179]
I want to upload files like mp3, but i cann't find the function in JBot code, can anyone help me plz

**Comment by Lionelsy** [comment]
LoL. Just like the issue166.
You can try the steps in the following:
First, replace the code:
```
   /**
 * Invoked when the bot receives a direct mention (@botname: message) or a
 * direct message. NOTE: These two event types are added by jbot to make your
 * task easier, Slack doesn't have any direct way to determine these type of
 * events.
 *
 * @param session
 * @param event
 */
@Controller(events = { EventType.DIRECT_MENTION, EventType.DIRECT_MESSAGE })
public void onReceiveDM(WebSocketSession session, Event event) {
    if (event.getText().contains("music")) {
        try {
            postFileToSlack(session, event);
        } catch (Exception e) {
            ;
        }
    } else {
        reply(session, event, "Hi, I am " + slackService.getCurrentUser().getName());
    }
}

/**
 * Invoked when bot receives an event of type DIRECT_MENTION or DIRECT_MESSAGE
 * with text containing "music"
 *
 * @param session: The seesion between slack and jbot
 * @param event:   including the main message prefer to send
 */
public void postFileToSlack(WebSocketSession session, Event event) throws IOException {
    File file = new File("Wait.mp3");
    okhttp3.Response response = new Meteoroid.Builder().token(slackToken).channels(event.getChannelId())
            .uploadFile(file).build().post();
    reply(session, event, "Enjoy the music!");
    response.close();
}
```
in [SlackBot.java](https://github.com/rampatra/jbot/blob/master/jbot-example/src/main/java/example/jbot/slack/SlackBot.java#L47-L59)

Here you need to install the okhttp3 and Meteoroid,
(For Convenience), i just download the [Meteoroid.java](https://github.com/operando/Meteoroid/blob/master/src/main/java/com/os/operando/meteoroid/Meteoroid.java) to the same directory of [SlackBot.java](https://github.com/rampatra/jbot/blob/master/jbot-example/src/main/java/example/jbot/slack/SlackBot.java)

You can add more check or operations to send different files.

The result as shown:
(Here due to the bandwidth in my server. So it seems slow.)
<img width="528" alt="Screen Shot 2020-05-31 at 16 03 19" src="https://user-images.githubusercontent.com/44608444/83347537-43503180-a358-11ea-832b-9a3b1005992e.png">

**Comment by Lionelsy** [comment]
LoL. Just like the issue166.
You can try the steps in the following:
First, replace the code:
```
   /**
 * Invoked when the bot receives a direct mention (@botname: message) or a
 * direct message. NOTE: These two event types are added by jbot to make your
 * task easier, Slack doesn't have any direct way to determine these type of
 * events.
 *
 * @param session
 * @param event
 */
@Controller(events = { EventType.DIRECT_MENTION, EventType.DIRECT_MESSAGE })
public void onReceiveDM(WebSocketSession session, Event event) {
    if (event.getText().contains("music")) {
        try {
            postFileToSlack(session, event);
        } catch (Exception e) {
            ;
        }
    } else {
        reply(session, event, "Hi, I am " + slackService.getCurrentUser().getName());
    }
}

/**
 * Invoked when bot receives an event of type DIRECT_MENTION or DIRECT_MESSAGE
 * with text containing "music"
 *
 * @param session: The seesion between slack and jbot
 * @param event:   including the main message prefer to send
 */
public void postFileToSlack(WebSocketSession session, Event event) throws IOException {
    File file = new File("Wait.mp3");
    okhttp3.Response response = new Meteoroid.Builder().token(slackToken).channels(event.getChannelId())
            .uploadFile(file).build().post();
    reply(session, event, "Enjoy the music!");
    response.close();
}
```
in [SlackBot.java](https://github.com/rampatra/jbot/blob/master/jbot-example/src/main/java/example/jbot/slack/SlackBot.java#L47-L59)

Here you need to install the okhttp3 and Meteoroid,
(For Convenience), i just download the [Meteoroid.java](https://github.com/operando/Meteoroid/blob/master/src/main/java/com/os/operando/meteoroid/Meteoroid.java) to the same directory of [SlackBot.java](https://github.com/rampatra/jbot/blob/master/jbot-example/src/main/java/example/jbot/slack/SlackBot.java)

You can add more check or operations to send different files.

The result as shown:
(Here due to the bandwidth in my server. So it seems slow.)
<img width="553" alt="Screen Shot 2020-05-31 at 18 25 14" src="https://user-images.githubusercontent.com/44608444/83350088-27ef2180-a36c-11ea-8ff4-e70177b34708.png">

**Comment by MOEVR** [comment]
Get it, thank you a lot
